language: php

matrix:
    include:
        - php: 7.3
        - php: nightly
    fast_finish: true
    allow_failures:
        - php: nightly

before_script:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-text

after_success:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar

